version: '3'
services:

  apiserver:
    container_name: apiserver
    build: ./node
  # ポートの指定(ホスト:コンテナ)
    ports:
      - "3000:3000"
    links:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: challecare
      MYSQL_PASSWORD: challecare
      MYSQL_ROOT_PASSWORD: challecare
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - challecare-mariadb:/var/lib/mysql
      - ./mariadb/initdb:/docker-entrypoint-initdb.d

volumes:
  challecare-mariadb: {}